# Generated by Django 4.1.3 on 2022-12-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_owner_alter_survey_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='owner',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.survey'),
        ),
    ]
