# Generated by Django 4.1.3 on 2022-12-09 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_remove_survey_question_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owvner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
