# Generated by Django 4.1.3 on 2022-12-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_owvner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owvner',
        ),
    ]
