# Generated by Django 4.1.3 on 2022-12-16 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 5, 25, 54, 468683), verbose_name='date published'),
        ),
    ]
